package com.idfc.ai.runbook.orchestration;
public enum RunbookJobState { RECEIVED, PREPARING_WORKSPACE, EXTRACTING, VALIDATING, NORMALIZING, DIFFING, RENDERING, READY_TO_PUBLISH, RENDERED_PUBLISH_BLOCKED, NO_OPERATIONAL_CHANGE, PUBLISHING, PUBLISHED, FAILED }
