package com.idfc.ai.runbook.normalization;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.util.*;
import java.util.regex.*;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;

@Component
public class RunbookNormalizer {
  private static final List<String> SECTIONS = List.of("businessFlows","businessRules","supportClassificationRules","apis","requestFields","conditionalValidations","responseMappings","errorCodes","referenceData","dataLineage","transformations","defaults","states","stateTransitions","sideEffects","recoveryMechanisms","databaseTables","aerospike","kafkaConsumers","kafkaProducers","downstreamDependencies","featureFlags","duplicateProtection","rateLimits","capacityConstraints","retentionRules","resilience","logSignatures","traceIdentifiers","configuredAlerts","supportHealthChecks","migrationRisks","unknownIncidentContext","escalationEvidence","unresolvedConfiguration","configuration");
  private final ObjectMapper mapper; private final StableIdService ids;
  @Autowired public RunbookNormalizer(ObjectMapper mapper, StableIdService ids){this.mapper=mapper;this.ids=ids;}
  public RunbookNormalizer(ObjectMapper mapper){this(mapper,new StableIdService());}
  public JsonNode normalize(JsonNode source){ObjectNode root=(ObjectNode)norm(source.deepCopy());for(String section:SECTIONS){ArrayNode values=root.withArray(section);for(JsonNode value:values)if(value instanceof ObjectNode entity)assignId(section,entity);sort(values);}root.withObject("idempotency");return root;}
  private JsonNode norm(JsonNode node){if(node instanceof ObjectNode object){TreeMap<String,JsonNode> fields=new TreeMap<>();object.fields().forEachRemaining(e->{if(!e.getValue().isNull()&&!(e.getValue().isTextual()&&e.getValue().asText().isBlank()))fields.put(e.getKey(),norm(e.getValue()));});if(fields.containsKey("timeout")&&!fields.containsKey("timeoutMs")){Integer value=duration(fields.remove("timeout").asText());if(value!=null)fields.put("timeoutMs",mapper.getNodeFactory().numberNode(value));}if(fields.containsKey("timeoutMs")){Integer value=duration(fields.get("timeoutMs").asText());if(value!=null)fields.put("timeoutMs",mapper.getNodeFactory().numberNode(value));}if(fields.containsKey("method"))fields.put("method",mapper.getNodeFactory().textNode(fields.get("method").asText().toUpperCase(Locale.ROOT)));if(fields.containsKey("access"))fields.put("access",mapper.getNodeFactory().textNode(fields.get("access").asText().toUpperCase(Locale.ROOT).replace('/','_')));ObjectNode ordered=mapper.createObjectNode();fields.forEach(ordered::set);return ordered;}if(node instanceof ArrayNode array){ArrayNode result=mapper.createArrayNode();array.forEach(v->result.add(norm(v)));return result;}if(node.isTextual())return mapper.getNodeFactory().textNode(node.asText().replaceAll("\\s+"," ").trim());return node;}
  private void assignId(String section,ObjectNode e){if(e.hasNonNull("id")||e.hasNonNull("stableId")){if(!e.hasNonNull("id"))e.set("id",e.get("stableId"));return;}String id=switch(section){case "configuration"->e.has("propertyKey")?ids.configuration(e.hasNonNull("componentId")?e.path("componentId").asText():(e.hasNonNull("modulePath")?e.path("modulePath").asText():(e.hasNonNull("deploymentUnit")?e.path("deploymentUnit").asText():null)),e.path("propertyKey").asText()):null;case "apis"->e.has("method")&&e.has("path")?ids.natural("API",e.path("method").asText(),e.path("path").asText()):null;case "kafkaConsumers"->e.has("topic")&&e.has("group")?ids.natural("KAFKA_CONSUMER",e.path("topic").asText(),e.path("group").asText()):null;case "kafkaProducers"->e.has("topic")?ids.natural("KAFKA_PRODUCER",e.path("topic").asText()):null;case "databaseTables"->e.has("table")?ids.natural("DB_TABLE",e.path("schema").asText("public"),e.path("table").asText()):null;case "downstreamDependencies"->e.has("name")?ids.natural("DEPENDENCY",e.path("name").asText()):null;case "featureFlags"->e.has("property")?ids.natural("FEATURE_FLAG",e.path("property").asText()):null;case "businessRules"->e.has("flowId")&&e.has("condition")?ids.businessRule(e.path("flowId").asText(),e.path("sourceFile").asText(),e.path("method").asText(),e.path("condition").asText()):null;default->null;};if(id!=null)e.put("id",id);}
  private void sort(ArrayNode values){List<JsonNode> ordered=new ArrayList<>();values.forEach(ordered::add);ordered.sort(Comparator.comparing(v->v.path("id").asText(v.toString())));values.removeAll();values.addAll(ordered);}
  private Integer duration(String value){Matcher m=Pattern.compile("(?i)^\\s*(\\d+(?:\\.\\d+)?)\\s*(ms|milliseconds?|s|seconds?)\\s*$").matcher(value);return !m.matches()?null:(int)(Double.parseDouble(m.group(1))*(m.group(2).toLowerCase(Locale.ROOT).startsWith("s")?1000:1));}
}
